# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2658034aa340e3f94cc0ec2918d96872400010c5fd7a5a0a869b6f051f23e1475bea3a808b79c0defad45f2a8192c47f2b36ca057ee673adfa5e04f763ea08b5

test:
  secret_key_base: fb0fffff8123d704476b41342184a831718a6410a89b6fbacadae85ba73278ea060c39af3fe2903f879ac273c2c2f97d17718676bea689b39a1f1a00784f7143

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
